/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulosRouteImport } from './routes/modulos'
import { Route as ModuloSlugRouteImport } from './routes/modulo.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosRoute = ModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuloSlugRoute = ModuloSlugRouteImport.update({
  id: '/modulo/$slug',
  path: '/modulo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modulos': typeof ModulosRoute
  '/modulo/$slug': typeof ModuloSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modulos': typeof ModulosRoute
  '/modulo/$slug': typeof ModuloSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modulos': typeof ModulosRoute
  '/modulo/$slug': typeof ModuloSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/modulos' | '/modulo/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modulos' | '/modulo/$slug'
  id: '__root__' | '/' | '/modulos' | '/modulo/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModulosRoute: typeof ModulosRoute
  ModuloSlugRoute: typeof ModuloSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos': {
      id: '/modulos'
      path: '/modulos'
      fullPath: '/modulos'
      preLoaderRoute: typeof ModulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo/$slug': {
      id: '/modulo/$slug'
      path: '/modulo/$slug'
      fullPath: '/modulo/$slug'
      preLoaderRoute: typeof ModuloSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModulosRoute: ModulosRoute,
  ModuloSlugRoute: ModuloSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
